/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package permata.medika.clinic.center;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author nico
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */

    public MainPage() {
        initComponents();
        
 
        setJumlahDokter();
        setJumlahPoli();
        setJumlahPasien();
        setJumlahKaryawan();
        getComboRM();
        getComboPoli();
        getDataRekamMedis();
        getIDKeluhanOtomatis();
        getIDRekamMedis();
        getIDKaryawan();
        getDataDokter();
        panel_tambah_dokter.setVisible(false);
        panel_edit_dokter.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_sidebar = new javax.swing.JPanel();
        sidebar_owner = new javax.swing.JPanel();
        link_owner_logout = new javax.swing.JLabel();
        link_owner_rekammedis = new javax.swing.JLabel();
        link_owner_dokter = new javax.swing.JLabel();
        link_owner_karyawan = new javax.swing.JLabel();
        link_owner_dashboard = new javax.swing.JLabel();
        clicked_owner_logout = new javax.swing.JLabel();
        clicked_owner_rekammedis = new javax.swing.JLabel();
        clicked_owner_dokter = new javax.swing.JLabel();
        clicked_owner_karyawan = new javax.swing.JLabel();
        clicked_owner_dashboard = new javax.swing.JLabel();
        bg_sidebar_owner = new javax.swing.JLabel();
        sidebar_admin = new javax.swing.JPanel();
        link_keluhan = new javax.swing.JLabel();
        clicked_link_keluhan = new javax.swing.JLabel();
        link_dashboard = new javax.swing.JLabel();
        clicked_link_dashboard = new javax.swing.JLabel();
        link_pendaftaran_pasien = new javax.swing.JLabel();
        clicked_link_pasien = new javax.swing.JLabel();
        link_rekam_medis = new javax.swing.JLabel();
        clicked_link_rekammedis = new javax.swing.JLabel();
        link_logout = new javax.swing.JLabel();
        clicked_link_logout = new javax.swing.JLabel();
        bg_sidebar_admin = new javax.swing.JLabel();
        panel_content = new javax.swing.JPanel();
        owner_rekammedis = new javax.swing.JPanel();
        jscroll_tabel_rekam_medis1 = new javax.swing.JScrollPane();
        tabel_rekam_medis_karyawan = new javax.swing.JTable();
        bg_dashboard4 = new javax.swing.JLabel();
        owner_dokter = new javax.swing.JPanel();
        panel_edit_dokter = new javax.swing.JPanel();
        jd_ttl_dokter_edit = new com.toedter.calendar.JDateChooser();
        btn_update_dokter = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        alamat_dokter_edit = new javax.swing.JTextArea();
        cmb_poli_dokter_edit = new javax.swing.JComboBox<>();
        cmb_kelamin_edit = new javax.swing.JComboBox<>();
        tf_input_jadwal_dokter_edit = new javax.swing.JTextField();
        tf_nik_dokter_edit = new javax.swing.JTextField();
        tf_no_dokter_edit = new javax.swing.JTextField();
        tf_nama_dokter_edit = new javax.swing.JTextField();
        tf_id_dokter_edit = new javax.swing.JTextField();
        btn_batal_tambah_dokter1 = new javax.swing.JLabel();
        bg_tambah_dokter1 = new javax.swing.JLabel();
        panel_tambah_dokter = new javax.swing.JPanel();
        jd_ttl_dokter = new com.toedter.calendar.JDateChooser();
        btn_input_dokter = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        alamat_dokter = new javax.swing.JTextArea();
        cmb_poli_tujuan_dokter = new javax.swing.JComboBox<>();
        cmb_kelamin_dokter = new javax.swing.JComboBox<>();
        tf_input_jadwal_dokter = new javax.swing.JTextField();
        tf_nik_dokter = new javax.swing.JTextField();
        tf_no_dokter = new javax.swing.JTextField();
        tf_nama_dokter = new javax.swing.JTextField();
        tf_id_dokter = new javax.swing.JTextField();
        btn_batal_tambah_dokter = new javax.swing.JLabel();
        bg_tambah_dokter = new javax.swing.JLabel();
        jscroll_tabel_rekam_medis2 = new javax.swing.JScrollPane();
        tabel_dokter = new javax.swing.JTable();
        btn_hapus_dokter = new javax.swing.JLabel();
        btn_tambah_dokter = new javax.swing.JLabel();
        btn_edit_dokter = new javax.swing.JLabel();
        bg_dashboard3 = new javax.swing.JLabel();
        owner_karyawan = new javax.swing.JPanel();
        tf_password_karyawan = new javax.swing.JTextField();
        tf_no_karyawan = new javax.swing.JTextField();
        tf_username_karyawan = new javax.swing.JTextField();
        tf_nik_karyawan = new javax.swing.JTextField();
        tf_id_karyawan = new javax.swing.JTextField();
        tf_nama_karyawan = new javax.swing.JTextField();
        cmb_jenis_kelamin_karyawan = new javax.swing.JComboBox<>();
        btn_tambah_karyawan = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_alamat_karyawan = new javax.swing.JTextArea();
        tanggal_lahir = new com.toedter.calendar.JDateChooser();
        bg_dashboard2 = new javax.swing.JLabel();
        owner_dashboard = new javax.swing.JPanel();
        lbl_jumlah_pegawai_owner = new javax.swing.JLabel();
        lbl_jumlah_poli_owner = new javax.swing.JLabel();
        lbl_jumlah_dokter_owner = new javax.swing.JLabel();
        lbl_total_pasien_owner = new javax.swing.JLabel();
        bg_dashboard1 = new javax.swing.JLabel();
        menu_dashboard = new javax.swing.JPanel();
        lbl_jumlah_poli = new javax.swing.JLabel();
        lbl_jumlah_dokter = new javax.swing.JLabel();
        lbl_total_pasien = new javax.swing.JLabel();
        bg_dashboard = new javax.swing.JLabel();
        menu_pendaftaran = new javax.swing.JPanel();
        tf_id_pasien = new javax.swing.JTextField();
        btn_simpan_pasien = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_alamat = new javax.swing.JTextArea();
        jd_tanggal_lahir = new com.toedter.calendar.JDateChooser();
        tf_no_bpjs = new javax.swing.JTextField();
        tf_nomor_telepon = new javax.swing.JTextField();
        tf_nik = new javax.swing.JTextField();
        tf_nama_lengkap = new javax.swing.JTextField();
        cmb_kelamin = new javax.swing.JComboBox<>();
        cmb_agama = new javax.swing.JComboBox<>();
        cmb_status_pernikahan = new javax.swing.JComboBox<>();
        cmb_poli = new javax.swing.JComboBox<>();
        bg_pendaftaran = new javax.swing.JLabel();
        cmb_poli1 = new javax.swing.JComboBox<>();
        menu_keluhan = new javax.swing.JPanel();
        tf_id_keluhan = new javax.swing.JTextField();
        btn_simpan_keluhan = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_keluhan = new javax.swing.JTextArea();
        tf_jadwal_dokter = new javax.swing.JTextField();
        tf_nik_keluhan = new javax.swing.JTextField();
        tf_nama_lengkap_keluhan = new javax.swing.JTextField();
        cmb_dokter = new javax.swing.JComboBox<>();
        cmb_poli_tujuan = new javax.swing.JComboBox<>();
        cmb_rekam_medis = new javax.swing.JComboBox<>();
        bg_keluhan = new javax.swing.JLabel();
        menu_rekammedis = new javax.swing.JPanel();
        jscroll_tabel_rekam_medis = new javax.swing.JScrollPane();
        tabel_rekam_medis = new javax.swing.JTable();
        bg_rekammedis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panel_sidebar.setLayout(null);

        sidebar_owner.setLayout(null);
        sidebar_owner.add(link_owner_logout);
        link_owner_logout.setBounds(10, 410, 220, 40);

        link_owner_rekammedis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                link_owner_rekammedisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                link_owner_rekammedisMouseEntered(evt);
            }
        });
        sidebar_owner.add(link_owner_rekammedis);
        link_owner_rekammedis.setBounds(10, 350, 220, 40);

        link_owner_dokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                link_owner_dokterMouseClicked(evt);
            }
        });
        sidebar_owner.add(link_owner_dokter);
        link_owner_dokter.setBounds(10, 290, 220, 40);

        link_owner_karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                link_owner_karyawanMouseClicked(evt);
            }
        });
        sidebar_owner.add(link_owner_karyawan);
        link_owner_karyawan.setBounds(10, 220, 220, 50);

        link_owner_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                link_owner_dashboardMouseClicked(evt);
            }
        });
        sidebar_owner.add(link_owner_dashboard);
        link_owner_dashboard.setBounds(10, 160, 220, 50);

        clicked_owner_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/effect-owner/btn-logout-white.png"))); // NOI18N
        sidebar_owner.add(clicked_owner_logout);
        clicked_owner_logout.setBounds(12, 407, 220, 50);

        clicked_owner_rekammedis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/effect-owner/btn-rekammedis-white.png"))); // NOI18N
        sidebar_owner.add(clicked_owner_rekammedis);
        clicked_owner_rekammedis.setBounds(12, 345, 220, 50);

        clicked_owner_dokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/effect-owner/btn-pegawai-white-1.png"))); // NOI18N
        sidebar_owner.add(clicked_owner_dokter);
        clicked_owner_dokter.setBounds(12, 283, 220, 50);

        clicked_owner_karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/effect-owner/btn-pegawai-white.png"))); // NOI18N
        sidebar_owner.add(clicked_owner_karyawan);
        clicked_owner_karyawan.setBounds(12, 221, 220, 50);

        clicked_owner_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/effect-owner/btn-dashboard-white.png"))); // NOI18N
        sidebar_owner.add(clicked_owner_dashboard);
        clicked_owner_dashboard.setBounds(12, 159, 220, 50);

        bg_sidebar_owner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sidebar-ownerpng.png"))); // NOI18N
        sidebar_owner.add(bg_sidebar_owner);
        bg_sidebar_owner.setBounds(0, 0, 236, 856);

        panel_sidebar.add(sidebar_owner);
        sidebar_owner.setBounds(0, 0, 236, 860);

        sidebar_admin.setLayout(null);

        link_keluhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                link_keluhanMouseClicked(evt);
            }
        });
        sidebar_admin.add(link_keluhan);
        link_keluhan.setBounds(10, 270, 210, 50);

        clicked_link_keluhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/effect/link-keluhan-white-1.png"))); // NOI18N
        clicked_link_keluhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clicked_link_keluhanMouseClicked(evt);
            }
        });
        sidebar_admin.add(clicked_link_keluhan);
        clicked_link_keluhan.setBounds(13, 269, 212, 50);

        link_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                link_dashboardMouseClicked(evt);
            }
        });
        sidebar_admin.add(link_dashboard);
        link_dashboard.setBounds(20, 130, 200, 50);

        clicked_link_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/effect/link-dashbord-white.png"))); // NOI18N
        clicked_link_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clicked_link_dashboardMouseClicked(evt);
            }
        });
        sidebar_admin.add(clicked_link_dashboard);
        clicked_link_dashboard.setBounds(12, 133, 220, 50);

        link_pendaftaran_pasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                link_pendaftaran_pasienMouseClicked(evt);
            }
        });
        sidebar_admin.add(link_pendaftaran_pasien);
        link_pendaftaran_pasien.setBounds(10, 210, 210, 40);

        clicked_link_pasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/effect/link-pendaftaran-white-1.png"))); // NOI18N
        clicked_link_pasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clicked_link_pasienMouseClicked(evt);
            }
        });
        sidebar_admin.add(clicked_link_pasien);
        clicked_link_pasien.setBounds(13, 201, 220, 50);

        link_rekam_medis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                link_rekam_medisMouseClicked(evt);
            }
        });
        sidebar_admin.add(link_rekam_medis);
        link_rekam_medis.setBounds(20, 340, 200, 40);

        clicked_link_rekammedis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/effect/link-rekammedis-white-1.png"))); // NOI18N
        clicked_link_rekammedis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clicked_link_rekammedisMouseClicked(evt);
            }
        });
        sidebar_admin.add(clicked_link_rekammedis);
        clicked_link_rekammedis.setBounds(12, 337, 220, 50);

        link_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                link_logoutMouseClicked(evt);
            }
        });
        sidebar_admin.add(link_logout);
        link_logout.setBounds(20, 410, 200, 50);

        clicked_link_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/effect/link-logout-white-1.png"))); // NOI18N
        clicked_link_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clicked_link_logoutMouseClicked(evt);
            }
        });
        sidebar_admin.add(clicked_link_logout);
        clicked_link_logout.setBounds(12, 405, 220, 50);

        bg_sidebar_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sidebar-admin.png"))); // NOI18N
        sidebar_admin.add(bg_sidebar_admin);
        bg_sidebar_admin.setBounds(0, 0, 236, 856);

        panel_sidebar.add(sidebar_admin);
        sidebar_admin.setBounds(0, 0, 236, 860);

        getContentPane().add(panel_sidebar);
        panel_sidebar.setBounds(0, 0, 236, 860);

        panel_content.setLayout(null);

        owner_rekammedis.setBackground(new java.awt.Color(102, 255, 0));
        owner_rekammedis.setLayout(null);

        tabel_rekam_medis_karyawan.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tabel_rekam_medis_karyawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nomor RM", "Nama", "Alamat", "Tanggal", "Layanan", "Aksi"
            }
        ));
        tabel_rekam_medis_karyawan.setRowHeight(40);
        jscroll_tabel_rekam_medis1.setViewportView(tabel_rekam_medis_karyawan);

        owner_rekammedis.add(jscroll_tabel_rekam_medis1);
        jscroll_tabel_rekam_medis1.setBounds(100, 310, 1080, 460);

        bg_dashboard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/halaman-admin/Rekam Medis - Pemilik.png"))); // NOI18N
        owner_rekammedis.add(bg_dashboard4);
        bg_dashboard4.setBounds(0, 0, 1276, 856);

        panel_content.add(owner_rekammedis);
        owner_rekammedis.setBounds(0, 0, 1276, 856);

        owner_dokter.setBackground(new java.awt.Color(102, 255, 0));
        owner_dokter.setLayout(null);

        panel_edit_dokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_edit_dokterMouseEntered(evt);
            }
        });
        panel_edit_dokter.setLayout(null);
        panel_edit_dokter.add(jd_ttl_dokter_edit);
        jd_ttl_dokter_edit.setBounds(660, 260, 360, 50);

        btn_update_dokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_update_dokterMouseClicked(evt);
            }
        });
        panel_edit_dokter.add(btn_update_dokter);
        btn_update_dokter.setBounds(490, 730, 130, 40);

        alamat_dokter_edit.setColumns(20);
        alamat_dokter_edit.setRows(5);
        jScrollPane5.setViewportView(alamat_dokter_edit);

        panel_edit_dokter.add(jScrollPane5);
        jScrollPane5.setBounds(670, 520, 350, 100);

        cmb_poli_dokter_edit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Pilih Poli Tujuan ---" }));
        cmb_poli_dokter_edit.setBorder(null);
        panel_edit_dokter.add(cmb_poli_dokter_edit);
        cmb_poli_dokter_edit.setBounds(230, 620, 380, 50);

        cmb_kelamin_edit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Pilih Kelamin ---", "Laki - Laki", "Perempuan" }));
        cmb_kelamin_edit.setBorder(null);
        panel_edit_dokter.add(cmb_kelamin_edit);
        cmb_kelamin_edit.setBounds(230, 520, 380, 50);

        tf_input_jadwal_dokter_edit.setBackground(new Color(0,0,0,0));
        tf_input_jadwal_dokter_edit.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_input_jadwal_dokter_edit.setBorder(null);
        tf_input_jadwal_dokter_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_input_jadwal_dokter_editActionPerformed(evt);
            }
        });
        panel_edit_dokter.add(tf_input_jadwal_dokter_edit);
        tf_input_jadwal_dokter_edit.setBounds(680, 430, 340, 50);

        tf_nik_dokter_edit.setBackground(new Color(0,0,0,0));
        tf_nik_dokter_edit.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_nik_dokter_edit.setBorder(null);
        tf_nik_dokter_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nik_dokter_editActionPerformed(evt);
            }
        });
        panel_edit_dokter.add(tf_nik_dokter_edit);
        tf_nik_dokter_edit.setBounds(250, 430, 340, 50);

        tf_no_dokter_edit.setBackground(new Color(0,0,0,0));
        tf_no_dokter_edit.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_no_dokter_edit.setBorder(null);
        tf_no_dokter_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_no_dokter_editActionPerformed(evt);
            }
        });
        panel_edit_dokter.add(tf_no_dokter_edit);
        tf_no_dokter_edit.setBounds(670, 350, 340, 50);

        tf_nama_dokter_edit.setBackground(new Color(0,0,0,0));
        tf_nama_dokter_edit.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_nama_dokter_edit.setBorder(null);
        tf_nama_dokter_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nama_dokter_editActionPerformed(evt);
            }
        });
        panel_edit_dokter.add(tf_nama_dokter_edit);
        tf_nama_dokter_edit.setBounds(250, 350, 340, 50);

        tf_id_dokter_edit.setBackground(new Color(0,0,0,0));
        tf_id_dokter_edit.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_id_dokter_edit.setBorder(null);
        tf_id_dokter_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_id_dokter_editActionPerformed(evt);
            }
        });
        panel_edit_dokter.add(tf_id_dokter_edit);
        tf_id_dokter_edit.setBounds(250, 260, 340, 50);

        btn_batal_tambah_dokter1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_batal_tambah_dokter1MouseClicked(evt);
            }
        });
        panel_edit_dokter.add(btn_batal_tambah_dokter1);
        btn_batal_tambah_dokter1.setBounds(640, 730, 130, 40);

        bg_tambah_dokter1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/halaman-admin/Edit Data Dokter - Pemilik.png"))); // NOI18N
        panel_edit_dokter.add(bg_tambah_dokter1);
        bg_tambah_dokter1.setBounds(0, 0, 1280, 860);

        owner_dokter.add(panel_edit_dokter);
        panel_edit_dokter.setBounds(0, 0, 1280, 860);

        panel_tambah_dokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_tambah_dokterMouseEntered(evt);
            }
        });
        panel_tambah_dokter.setLayout(null);
        panel_tambah_dokter.add(jd_ttl_dokter);
        jd_ttl_dokter.setBounds(660, 260, 360, 50);

        btn_input_dokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_input_dokterMouseClicked(evt);
            }
        });
        panel_tambah_dokter.add(btn_input_dokter);
        btn_input_dokter.setBounds(490, 730, 130, 40);

        alamat_dokter.setColumns(20);
        alamat_dokter.setRows(5);
        jScrollPane4.setViewportView(alamat_dokter);

        panel_tambah_dokter.add(jScrollPane4);
        jScrollPane4.setBounds(670, 520, 350, 100);

        cmb_poli_tujuan_dokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Pilih Poli Tujuan ---", "Belum Nikah", "Sudah Nikah" }));
        cmb_poli_tujuan_dokter.setBorder(null);
        panel_tambah_dokter.add(cmb_poli_tujuan_dokter);
        cmb_poli_tujuan_dokter.setBounds(230, 620, 380, 50);

        cmb_kelamin_dokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Pilih Kelamin ---", "Laki - Laki", "Perempuan" }));
        cmb_kelamin_dokter.setBorder(null);
        panel_tambah_dokter.add(cmb_kelamin_dokter);
        cmb_kelamin_dokter.setBounds(230, 520, 380, 50);

        tf_input_jadwal_dokter.setBackground(new Color(0,0,0,0));
        tf_input_jadwal_dokter.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_input_jadwal_dokter.setBorder(null);
        tf_input_jadwal_dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_input_jadwal_dokterActionPerformed(evt);
            }
        });
        panel_tambah_dokter.add(tf_input_jadwal_dokter);
        tf_input_jadwal_dokter.setBounds(680, 430, 340, 50);

        tf_nik_dokter.setBackground(new Color(0,0,0,0));
        tf_nik_dokter.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_nik_dokter.setBorder(null);
        tf_nik_dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nik_dokterActionPerformed(evt);
            }
        });
        panel_tambah_dokter.add(tf_nik_dokter);
        tf_nik_dokter.setBounds(250, 430, 340, 50);

        tf_no_dokter.setBackground(new Color(0,0,0,0));
        tf_no_dokter.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_no_dokter.setBorder(null);
        tf_no_dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_no_dokterActionPerformed(evt);
            }
        });
        panel_tambah_dokter.add(tf_no_dokter);
        tf_no_dokter.setBounds(670, 350, 340, 50);

        tf_nama_dokter.setBackground(new Color(0,0,0,0));
        tf_nama_dokter.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_nama_dokter.setBorder(null);
        tf_nama_dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nama_dokterActionPerformed(evt);
            }
        });
        panel_tambah_dokter.add(tf_nama_dokter);
        tf_nama_dokter.setBounds(250, 350, 340, 50);

        tf_id_dokter.setBackground(new Color(0,0,0,0));
        tf_id_dokter.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_id_dokter.setBorder(null);
        tf_id_dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_id_dokterActionPerformed(evt);
            }
        });
        panel_tambah_dokter.add(tf_id_dokter);
        tf_id_dokter.setBounds(250, 260, 340, 50);

        btn_batal_tambah_dokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_batal_tambah_dokterMouseClicked(evt);
            }
        });
        panel_tambah_dokter.add(btn_batal_tambah_dokter);
        btn_batal_tambah_dokter.setBounds(640, 730, 130, 40);

        bg_tambah_dokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/halaman-admin/Tambah Data Dokter - Pemilik.png"))); // NOI18N
        panel_tambah_dokter.add(bg_tambah_dokter);
        bg_tambah_dokter.setBounds(0, 0, 1280, 860);

        owner_dokter.add(panel_tambah_dokter);
        panel_tambah_dokter.setBounds(0, 0, 1280, 860);

        tabel_dokter.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tabel_dokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Dokter", "Nama Dokter", "Jenis Kelamin", "Jadwal", "Nama Poli"
            }
        ));
        tabel_dokter.setRowHeight(40);
        jscroll_tabel_rekam_medis2.setViewportView(tabel_dokter);

        owner_dokter.add(jscroll_tabel_rekam_medis2);
        jscroll_tabel_rekam_medis2.setBounds(100, 310, 1080, 460);

        btn_hapus_dokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapus_dokterMouseClicked(evt);
            }
        });
        owner_dokter.add(btn_hapus_dokter);
        btn_hapus_dokter.setBounds(700, 180, 140, 60);

        btn_tambah_dokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambah_dokterMouseClicked(evt);
            }
        });
        owner_dokter.add(btn_tambah_dokter);
        btn_tambah_dokter.setBounds(330, 180, 180, 60);

        btn_edit_dokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_edit_dokterMouseClicked(evt);
            }
        });
        owner_dokter.add(btn_edit_dokter);
        btn_edit_dokter.setBounds(530, 180, 140, 60);

        bg_dashboard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/halaman-admin/Dokter - Pemilik.png"))); // NOI18N
        owner_dokter.add(bg_dashboard3);
        bg_dashboard3.setBounds(0, 0, 1276, 856);

        panel_content.add(owner_dokter);
        owner_dokter.setBounds(0, 0, 1276, 856);

        owner_karyawan.setBackground(new java.awt.Color(102, 255, 0));
        owner_karyawan.setLayout(null);

        tf_password_karyawan.setBackground(new Color(0,0,0,0));
        tf_password_karyawan.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_password_karyawan.setBorder(null);
        tf_password_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_password_karyawanActionPerformed(evt);
            }
        });
        owner_karyawan.add(tf_password_karyawan);
        tf_password_karyawan.setBounds(260, 520, 340, 50);

        tf_no_karyawan.setBackground(new Color(0,0,0,0));
        tf_no_karyawan.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_no_karyawan.setBorder(null);
        tf_no_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_no_karyawanActionPerformed(evt);
            }
        });
        owner_karyawan.add(tf_no_karyawan);
        tf_no_karyawan.setBounds(680, 430, 340, 50);

        tf_username_karyawan.setBackground(new Color(0,0,0,0));
        tf_username_karyawan.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_username_karyawan.setBorder(null);
        tf_username_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_username_karyawanActionPerformed(evt);
            }
        });
        owner_karyawan.add(tf_username_karyawan);
        tf_username_karyawan.setBounds(260, 430, 340, 50);

        tf_nik_karyawan.setBackground(new Color(0,0,0,0));
        tf_nik_karyawan.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_nik_karyawan.setBorder(null);
        tf_nik_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nik_karyawanActionPerformed(evt);
            }
        });
        owner_karyawan.add(tf_nik_karyawan);
        tf_nik_karyawan.setBounds(260, 350, 340, 50);

        tf_id_karyawan.setBackground(new Color(0,0,0,0));
        tf_id_karyawan.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_id_karyawan.setBorder(null);
        tf_id_karyawan.setEnabled(false);
        tf_id_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_id_karyawanActionPerformed(evt);
            }
        });
        owner_karyawan.add(tf_id_karyawan);
        tf_id_karyawan.setBounds(680, 260, 340, 50);

        tf_nama_karyawan.setBackground(new Color(0,0,0,0));
        tf_nama_karyawan.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_nama_karyawan.setBorder(null);
        tf_nama_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nama_karyawanActionPerformed(evt);
            }
        });
        owner_karyawan.add(tf_nama_karyawan);
        tf_nama_karyawan.setBounds(260, 260, 340, 50);

        cmb_jenis_kelamin_karyawan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Pilih Jenis Kelamin ---", "laki-laki", "perempuan" }));
        cmb_jenis_kelamin_karyawan.setBorder(null);
        owner_karyawan.add(cmb_jenis_kelamin_karyawan);
        cmb_jenis_kelamin_karyawan.setBounds(240, 610, 380, 50);

        btn_tambah_karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambah_karyawanMouseClicked(evt);
            }
        });
        owner_karyawan.add(btn_tambah_karyawan);
        btn_tambah_karyawan.setBounds(500, 730, 130, 40);

        ta_alamat_karyawan.setBackground(new Color(0,0,0,0));
        ta_alamat_karyawan.setColumns(20);
        ta_alamat_karyawan.setRows(5);
        ta_alamat_karyawan.setBorder(null);
        jScrollPane3.setViewportView(ta_alamat_karyawan);

        owner_karyawan.add(jScrollPane3);
        jScrollPane3.setBounds(680, 520, 340, 100);
        owner_karyawan.add(tanggal_lahir);
        tanggal_lahir.setBounds(660, 350, 380, 50);

        bg_dashboard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/halaman-admin/Karyawan -  Pemilik.png"))); // NOI18N
        owner_karyawan.add(bg_dashboard2);
        bg_dashboard2.setBounds(0, 0, 1276, 856);

        panel_content.add(owner_karyawan);
        owner_karyawan.setBounds(0, 0, 1276, 856);

        owner_dashboard.setBackground(new java.awt.Color(102, 255, 0));
        owner_dashboard.setLayout(null);

        lbl_jumlah_pegawai_owner.setFont(new java.awt.Font("Helvetica Neue", 1, 64)); // NOI18N
        lbl_jumlah_pegawai_owner.setForeground(new java.awt.Color(255, 255, 255));
        lbl_jumlah_pegawai_owner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_jumlah_pegawai_owner.setText("0");
        owner_dashboard.add(lbl_jumlah_pegawai_owner);
        lbl_jumlah_pegawai_owner.setBounds(1020, 230, 160, 100);

        lbl_jumlah_poli_owner.setFont(new java.awt.Font("Helvetica Neue", 1, 64)); // NOI18N
        lbl_jumlah_poli_owner.setForeground(new java.awt.Color(255, 255, 255));
        lbl_jumlah_poli_owner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_jumlah_poli_owner.setText("0");
        owner_dashboard.add(lbl_jumlah_poli_owner);
        lbl_jumlah_poli_owner.setBounds(770, 230, 120, 100);

        lbl_jumlah_dokter_owner.setFont(new java.awt.Font("Helvetica Neue", 1, 64)); // NOI18N
        lbl_jumlah_dokter_owner.setForeground(new java.awt.Color(255, 255, 255));
        lbl_jumlah_dokter_owner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_jumlah_dokter_owner.setText("0");
        owner_dashboard.add(lbl_jumlah_dokter_owner);
        lbl_jumlah_dokter_owner.setBounds(470, 230, 140, 100);

        lbl_total_pasien_owner.setFont(new java.awt.Font("Helvetica Neue", 1, 64)); // NOI18N
        lbl_total_pasien_owner.setForeground(new java.awt.Color(255, 255, 255));
        lbl_total_pasien_owner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_total_pasien_owner.setText("0");
        owner_dashboard.add(lbl_total_pasien_owner);
        lbl_total_pasien_owner.setBounds(200, 230, 120, 100);

        bg_dashboard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/halaman-admin/Dashboard - Pemilik.png"))); // NOI18N
        owner_dashboard.add(bg_dashboard1);
        bg_dashboard1.setBounds(0, 0, 1276, 856);

        panel_content.add(owner_dashboard);
        owner_dashboard.setBounds(0, 0, 1276, 856);

        menu_dashboard.setBackground(new java.awt.Color(102, 255, 0));
        menu_dashboard.setLayout(null);

        lbl_jumlah_poli.setFont(new java.awt.Font("Helvetica Neue", 1, 64)); // NOI18N
        lbl_jumlah_poli.setForeground(new java.awt.Color(255, 255, 255));
        lbl_jumlah_poli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_jumlah_poli.setText("0");
        menu_dashboard.add(lbl_jumlah_poli);
        lbl_jumlah_poli.setBounds(976, 230, 140, 100);

        lbl_jumlah_dokter.setFont(new java.awt.Font("Helvetica Neue", 1, 64)); // NOI18N
        lbl_jumlah_dokter.setForeground(new java.awt.Color(255, 255, 255));
        lbl_jumlah_dokter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_jumlah_dokter.setText("0");
        menu_dashboard.add(lbl_jumlah_dokter);
        lbl_jumlah_dokter.setBounds(596, 230, 170, 100);

        lbl_total_pasien.setFont(new java.awt.Font("Helvetica Neue", 1, 64)); // NOI18N
        lbl_total_pasien.setForeground(new java.awt.Color(255, 255, 255));
        lbl_total_pasien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_total_pasien.setText("0");
        menu_dashboard.add(lbl_total_pasien);
        lbl_total_pasien.setBounds(246, 230, 150, 100);

        bg_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/halaman-menu/Panel - Dashboard - Admin.png"))); // NOI18N
        menu_dashboard.add(bg_dashboard);
        bg_dashboard.setBounds(0, 0, 1276, 856);

        panel_content.add(menu_dashboard);
        menu_dashboard.setBounds(0, 0, 1276, 856);

        menu_pendaftaran.setBackground(new java.awt.Color(102, 255, 0));
        menu_pendaftaran.setLayout(null);

        tf_id_pasien.setBackground(new Color(0,0,0,0));
        tf_id_pasien.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_id_pasien.setBorder(null);
        tf_id_pasien.setEnabled(false);
        menu_pendaftaran.add(tf_id_pasien);
        tf_id_pasien.setBounds(50, 188, 340, 50);

        btn_simpan_pasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpan_pasienMouseClicked(evt);
            }
        });
        menu_pendaftaran.add(btn_simpan_pasien);
        btn_simpan_pasien.setBounds(920, 480, 110, 40);

        ta_alamat.setColumns(20);
        ta_alamat.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        ta_alamat.setLineWrap(true);
        ta_alamat.setRows(5);
        ta_alamat.setBorder(null);
        jScrollPane1.setViewportView(ta_alamat);

        menu_pendaftaran.add(jScrollPane1);
        jScrollPane1.setBounds(470, 470, 350, 100);
        menu_pendaftaran.add(jd_tanggal_lahir);
        jd_tanggal_lahir.setBounds(870, 190, 380, 50);

        tf_no_bpjs.setBackground(new Color(0,0,0,0));
        tf_no_bpjs.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_no_bpjs.setBorder(null);
        menu_pendaftaran.add(tf_no_bpjs);
        tf_no_bpjs.setBounds(890, 380, 340, 50);

        tf_nomor_telepon.setBackground(new Color(0,0,0,0));
        tf_nomor_telepon.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_nomor_telepon.setBorder(null);
        menu_pendaftaran.add(tf_nomor_telepon);
        tf_nomor_telepon.setBounds(50, 376, 340, 50);

        tf_nik.setBackground(new Color(0,0,0,0));
        tf_nik.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_nik.setBorder(null);
        tf_nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nikActionPerformed(evt);
            }
        });
        menu_pendaftaran.add(tf_nik);
        tf_nik.setBounds(470, 188, 340, 50);

        tf_nama_lengkap.setBackground(new Color(0,0,0,0));
        tf_nama_lengkap.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_nama_lengkap.setBorder(null);
        menu_pendaftaran.add(tf_nama_lengkap);
        tf_nama_lengkap.setBounds(50, 282, 340, 50);

        cmb_kelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Pilih Kelamin ---", "Laki - Laki", "Perempuan" }));
        cmb_kelamin.setBorder(null);
        menu_pendaftaran.add(cmb_kelamin);
        cmb_kelamin.setBounds(450, 283, 380, 50);

        cmb_agama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Pilih Agama ---", "Islam", "Protestan", "Katolik", "Hindu", "Budha", "Konghucu" }));
        cmb_agama.setBorder(null);
        menu_pendaftaran.add(cmb_agama);
        cmb_agama.setBounds(870, 288, 380, 50);

        cmb_status_pernikahan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Pilih Status ---", "Belum Nikah", "Sudah Nikah" }));
        cmb_status_pernikahan.setBorder(null);
        menu_pendaftaran.add(cmb_status_pernikahan);
        cmb_status_pernikahan.setBounds(450, 390, 380, 50);

        cmb_poli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Pilih Poli Tujuan ---", "Belum Nikah", "Sudah Nikah" }));
        cmb_poli.setBorder(null);
        menu_pendaftaran.add(cmb_poli);
        cmb_poli.setBounds(30, 480, 380, 50);

        bg_pendaftaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/halaman-menu/Panel Pendaftaran - Admin.png"))); // NOI18N
        menu_pendaftaran.add(bg_pendaftaran);
        bg_pendaftaran.setBounds(0, 0, 1276, 856);

        cmb_poli1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Pilih Poli Tujuan ---" }));
        cmb_poli1.setBorder(null);
        menu_pendaftaran.add(cmb_poli1);
        cmb_poli1.setBounds(30, 390, 380, 50);

        panel_content.add(menu_pendaftaran);
        menu_pendaftaran.setBounds(0, 0, 1276, 856);

        menu_keluhan.setBackground(new java.awt.Color(102, 255, 0));
        menu_keluhan.setLayout(null);

        tf_id_keluhan.setBackground(new Color(0,0,0,0));
        tf_id_keluhan.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_id_keluhan.setBorder(null);
        tf_id_keluhan.setEnabled(false);
        menu_keluhan.add(tf_id_keluhan);
        tf_id_keluhan.setBounds(470, 190, 330, 50);

        btn_simpan_keluhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpan_keluhanMouseClicked(evt);
            }
        });
        menu_keluhan.add(btn_simpan_keluhan);
        btn_simpan_keluhan.setBounds(520, 382, 110, 40);

        ta_keluhan.setColumns(20);
        ta_keluhan.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        ta_keluhan.setLineWrap(true);
        ta_keluhan.setRows(5);
        ta_keluhan.setBorder(null);
        jScrollPane2.setViewportView(ta_keluhan);

        menu_keluhan.add(jScrollPane2);
        jScrollPane2.setBounds(460, 380, 350, 100);

        tf_jadwal_dokter.setBackground(new Color(0,0,0,0));
        tf_jadwal_dokter.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_jadwal_dokter.setBorder(null);
        tf_jadwal_dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_jadwal_dokterActionPerformed(evt);
            }
        });
        menu_keluhan.add(tf_jadwal_dokter);
        tf_jadwal_dokter.setBounds(50, 380, 340, 50);

        tf_nik_keluhan.setBackground(new Color(0,0,0,0));
        tf_nik_keluhan.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_nik_keluhan.setBorder(null);
        menu_keluhan.add(tf_nik_keluhan);
        tf_nik_keluhan.setBounds(50, 276, 340, 50);

        tf_nama_lengkap_keluhan.setBackground(new Color(0,0,0,0));
        tf_nama_lengkap_keluhan.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tf_nama_lengkap_keluhan.setBorder(null);
        menu_keluhan.add(tf_nama_lengkap_keluhan);
        tf_nama_lengkap_keluhan.setBounds(890, 190, 340, 50);

        cmb_dokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Pilih Dokter ---" }));
        cmb_dokter.setBorder(null);
        cmb_dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_dokterActionPerformed(evt);
            }
        });
        menu_keluhan.add(cmb_dokter);
        cmb_dokter.setBounds(870, 280, 380, 50);

        cmb_poli_tujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Pilih Poli Tujuan ---" }));
        cmb_poli_tujuan.setBorder(null);
        cmb_poli_tujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_poli_tujuanActionPerformed(evt);
            }
        });
        menu_keluhan.add(cmb_poli_tujuan);
        cmb_poli_tujuan.setBounds(450, 280, 380, 50);

        cmb_rekam_medis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Pilih ID Rekam Medis ---" }));
        cmb_rekam_medis.setBorder(null);
        cmb_rekam_medis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_rekam_medisActionPerformed(evt);
            }
        });
        menu_keluhan.add(cmb_rekam_medis);
        cmb_rekam_medis.setBounds(30, 190, 380, 50);

        bg_keluhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/halaman-menu/Panel Keluhan Pasien - Admin.png"))); // NOI18N
        menu_keluhan.add(bg_keluhan);
        bg_keluhan.setBounds(0, 0, 1276, 856);

        panel_content.add(menu_keluhan);
        menu_keluhan.setBounds(0, 0, 1276, 856);

        menu_rekammedis.setBackground(new java.awt.Color(102, 255, 0));
        menu_rekammedis.setLayout(null);

        tabel_rekam_medis.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        tabel_rekam_medis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nomor RM", "Nama", "Alamat", "Tanggal", "Layanan", "Aksi"
            }
        ));
        tabel_rekam_medis.setRowHeight(40);
        jscroll_tabel_rekam_medis.setViewportView(tabel_rekam_medis);

        menu_rekammedis.add(jscroll_tabel_rekam_medis);
        jscroll_tabel_rekam_medis.setBounds(100, 310, 1080, 460);

        bg_rekammedis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/halaman-menu/Panel - Rekam Medis - Admin.png"))); // NOI18N
        menu_rekammedis.add(bg_rekammedis);
        bg_rekammedis.setBounds(0, 0, 1276, 856);

        panel_content.add(menu_rekammedis);
        menu_rekammedis.setBounds(0, 0, 1276, 856);

        getContentPane().add(panel_content);
        panel_content.setBounds(240, 0, 1270, 860);

        setBounds(0, 0, 1512, 884);
    }// </editor-fold>//GEN-END:initComponents
    
    public void getViewAdmin(){
        panel_sidebar.removeAll();
        panel_sidebar.repaint();
        panel_sidebar.revalidate();
        
        panel_sidebar.add(sidebar_admin);
        panel_sidebar.repaint();
        panel_sidebar.revalidate();
        clicked_link_dashboard.setVisible(true);
        clicked_link_pasien.setVisible(false);
        clicked_link_keluhan.setVisible(false);
        clicked_link_rekammedis.setVisible(false);
        clicked_link_logout.setVisible(false);
        panel_content.removeAll();
        panel_content.repaint();
        panel_content.revalidate();
        
        panel_content.add(menu_dashboard);
        panel_content.repaint();
        panel_content.revalidate();
    }
    
    public void getViewOwner(){
        panel_sidebar.removeAll();
        panel_sidebar.repaint();
        panel_sidebar.revalidate();
        
        panel_sidebar.add(sidebar_owner);
        panel_sidebar.repaint();
        panel_sidebar.revalidate();
        clicked_owner_dashboard.setVisible(true);
        clicked_owner_karyawan.setVisible(false);
        clicked_owner_dokter.setVisible(false);
        clicked_owner_rekammedis.setVisible(false);
        clicked_owner_logout.setVisible(false);
        panel_content.removeAll();
        panel_content.repaint();
        panel_content.revalidate();
        
        panel_content.add(owner_dashboard);
        panel_content.repaint();
        panel_content.revalidate();
    }
    
    public void getIDKaryawan(){
        try {
            String sql = "select id_karyawan from `tb_karyawan`";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            String lastNumber = null;
            while (res.next()) {
              lastNumber  = res.getString(1);
            };
            
            String twoLastChars = lastNumber.substring(lastNumber.length() - 2);
            int lastNumbers = Integer.parseInt(twoLastChars);
            int newID = lastNumbers + 1;
            if(newID >= 10){
                tf_id_karyawan.setText("IDK0" + newID);
            }else{
                tf_id_karyawan.setText("IDK00" + newID);
            }
        } catch (Exception e) {
            System.err.println("koneksi gagal " + e.getMessage());
        }
    }
    
    public void getIDKeluhanOtomatis(){
        try {
            String sql = "select id_keluhan from `tb_keluhan`";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            String lastNumber = null;
            while (res.next()) {
              lastNumber  = res.getString(1);
            };
            
            String twoLastChars = lastNumber.substring(lastNumber.length() - 2);
            int lastNumbers = Integer.parseInt(twoLastChars);
            int newID = lastNumbers + 1;
            if(newID >= 10){
                tf_id_keluhan.setText("IDKE" + newID);
            }else{
                tf_id_keluhan.setText("IDKE0" + newID);
            }
        } catch (Exception e) {
            System.err.println("koneksi gagal " + e.getMessage());
        }
    }
    
    public void getIDRekamMedis(){
        try {
            String sql = "select id_rekam_medis from `tb_pasien`";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            String lastNumber = null;
            while (res.next()) {
              lastNumber  = res.getString(1);
            };
            
            String twoLastChars = lastNumber.substring(lastNumber.length() - 2);
            int lastNumbers = Integer.parseInt(twoLastChars);
            int newID = lastNumbers + 1;
            if(newID >= 10){
                tf_id_pasien.setText("IDP0" + newID);
            }else{
                tf_id_pasien.setText("IDP00" + newID);
            }
        } catch (Exception e) {
            System.err.println("koneksi gagal " + e.getMessage());
        }
    }
    
    public void getDataRekamMedis(){
        try {
            String sql = "SELECT tb_keluhan.id_rekam_medis, tb_pasien.nama, tb_pasien.alamat, tb_keluhan.tanggal_pemeriksaan ,tb_keluhan.layanan FROM tb_keluhan JOIN tb_pasien ON tb_keluhan.id_rekam_medis = tb_pasien.id_rekam_medis;";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("Nomor RM");
            tbl.addColumn("Nama");
            tbl.addColumn("Alamat");
            tbl.addColumn("Tanggal Kontrol");
            tbl.addColumn("Layanan");
            tabel_rekam_medis.setModel(tbl);
            tabel_rekam_medis_karyawan.setModel(tbl);
            
            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5)
                });
                tabel_rekam_medis.setModel(tbl);
                tabel_rekam_medis_karyawan.setModel(tbl);
            };
            
        } catch (Exception e) {
            System.err.println("koneksi gagal " + e.getMessage());
        }
    }
    
    public void getDataDokter(){
        try {
            String sql = "SELECT * FROM tb_dokter";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("ID Dokter");
            tbl.addColumn("Nama Dokter");
            tbl.addColumn("Jenis Kelamin");
            tbl.addColumn("Jadwal");
            tbl.addColumn("Nama Poli");
            
            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString(1),
                    res.getString(2),
                    res.getString(6),
                    res.getString(7),
                    res.getString(8)
                });
                tabel_dokter.setModel(tbl);
            };
            
        } catch (Exception e) {
            System.err.println("koneksi gagal " + e.getMessage());
        }
    }
    
    public void setJadwalByIdDokter(){
        try {
            String ID_Dokter = (String)cmb_dokter.getSelectedItem();
            String sql = "select * from `tb_dokter` where id_dokter = '"+ID_Dokter+"'";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            
            while (res.next()) {
                tf_jadwal_dokter.setText(res.getString(7));
            };
            
        } catch (Exception e) {
            System.err.println("koneksi gagal " + e.getMessage());
        }
    }
    
    public void setDokterByIdPoli(){
        try {
            String ID_Poli = (String)cmb_poli_tujuan.getSelectedItem();
            String sql = "select * from `tb_dokter` where id_poli = '"+ID_Poli+"'";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            cmb_dokter.removeAllItems();
            while (res.next()) {
                cmb_dokter.addItem(res.getString(1));
                cmb_dokter.setSelectedItem(res.getString(1));
            };
            
        } catch (Exception e) {
            System.err.println("koneksi gagal " + e.getMessage());
        }
    }
    
    public void setDataByIdRM(){
        try {
            String ID_Rekam_Medis = (String)cmb_rekam_medis.getSelectedItem();
            String sql = "select * from `tb_pasien` where id_rekam_medis = '"+ID_Rekam_Medis+"'";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            
            while (res.next()) {
                tf_nama_lengkap_keluhan.setText(res.getString(2));
                tf_nik_keluhan.setText(res.getString(4));
            };
            
        } catch (Exception e) {
            System.err.println("koneksi gagal " + e.getMessage());
        }
    }
    
    public void getComboRM(){
        try {
            String sql = "select * from `tb_pasien`";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            
            while (res.next()) {
                cmb_rekam_medis.addItem(res.getString(1));
            };
            
        } catch (Exception e) {
            System.err.println("koneksi gagal " + e.getMessage());
        }
    }
    
    public void getComboPoli(){
        try {
            String sql = "select * from `tb_poli`";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            
            while (res.next()) {
                cmb_poli_tujuan.addItem(res.getString(1));
                cmb_poli_dokter_edit.addItem(res.getString(1));
            };
            
        } catch (Exception e) {
            System.err.println("koneksi gagal " + e.getMessage());
        }
    }
    
    public void getComboDokter(){
        try {
            String sql = "select * from `tb_dokter`";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            while (res.next()) {
                cmb_dokter.addItem(res.getString(1));
            };
            
        } catch (Exception e) {
            System.err.println("koneksi gagal " + e.getMessage());
        }
    }
    
    public static List<String[]> getData() {
        List<String[]> dataList = new ArrayList<>();

        try {
            String sql = "select * from tb_rekam_medis";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            while (res.next()) {
                String[] rowData = new String[]{
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6),
                    res.getString(7)
                };

                dataList.add(rowData);
                System.out.println(Arrays.toString(rowData));
            }
        } catch (Exception e) {
            System.err.println("koneksi gagal " + e.getMessage());
        }

        return dataList;
    }

    public void setJumlahPasien(){
        String hasil = null;
        try {
            String sql = "SELECT count('id_rekam_medis') as jumlah_rekam_medis FROM `tb_pasien`";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            if(res.next()){
                lbl_total_pasien.setText(res.getString(1));
                lbl_total_pasien_owner.setText(res.getString(1));
            }else{
                System.out.println("tidak ada data");
            }
        } catch (Exception e) {
            System.err.println("koneksi gagal " + e.getMessage());
        }
    }
    
    public void setJumlahDokter(){
        try {
            String sql = "SELECT count('id_dokter') as jumlah_dokter FROM `tb_dokter`";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            if(res.next()){
                lbl_jumlah_dokter.setText(res.getString(1));
                lbl_jumlah_dokter_owner.setText(res.getString(1));
            }else{
                System.out.println("tidak ada data");
            }
        } catch (Exception e) {
            System.err.println("koneksi gagal " + e.getMessage());
        }
    }
    
    public void setJumlahPoli(){
        String jumlah_poli = null;
        try {
            String sql = "SELECT count('id_poli') as jumlah_poli FROM `tb_poli`";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            if(res.next()){
                lbl_jumlah_poli.setText(res.getString(1));
                lbl_jumlah_poli_owner.setText(res.getString(1));
            }else{
                System.out.println("tidak ada data");
            }
        } catch (Exception e) {
            System.err.println("koneksi gagal " + e.getMessage());
        }
    }
    
    public void setJumlahKaryawan(){
        String jumlah_poli = null;
        try {
            String sql = "SELECT count('id_karyawan') as jumlah_karyawan FROM `tb_karyawan`";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            if(res.next()){
                lbl_jumlah_pegawai_owner.setText(res.getString(1));
            }else{
                System.out.println("tidak ada data");
            }
        } catch (Exception e) {
            System.err.println("koneksi gagal " + e.getMessage());
        }
    }

    private void link_pendaftaran_pasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link_pendaftaran_pasienMouseClicked

        panel_content.removeAll();
        panel_content.repaint();
        panel_content.revalidate();
        
        panel_content.add(menu_pendaftaran);
        panel_content.repaint();
        panel_content.revalidate();
        
        clicked_link_dashboard.setVisible(false);
        clicked_link_pasien.setVisible(true);
        clicked_link_keluhan.setVisible(false);
        clicked_link_rekammedis.setVisible(false);
        clicked_link_logout.setVisible(false);
    }//GEN-LAST:event_link_pendaftaran_pasienMouseClicked

    private void link_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link_dashboardMouseClicked
        panel_content.removeAll();
        panel_content.repaint();
        panel_content.revalidate();
        
        panel_content.add(menu_dashboard);
        panel_content.repaint();
        panel_content.revalidate();
        
        clicked_link_dashboard.setVisible(true);
        clicked_link_pasien.setVisible(false);
        clicked_link_keluhan.setVisible(false);
        clicked_link_rekammedis.setVisible(false);
        clicked_link_logout.setVisible(false);
        setJumlahPasien();
        setJumlahDokter();
        setJumlahPoli();
    }//GEN-LAST:event_link_dashboardMouseClicked

    private void link_rekam_medisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link_rekam_medisMouseClicked

        panel_content.removeAll();
        panel_content.repaint();
        panel_content.revalidate();
        
        panel_content.add(menu_rekammedis);
        panel_content.repaint();
        panel_content.revalidate();
//        List<String[]> rowData = getData();
//        if (rowData != null) {
//            rekamMedis.updateTable(rowData);
//        } else {
//            System.out.println("data dari db kososng");
//        }
        clicked_link_dashboard.setVisible(false);
        clicked_link_pasien.setVisible(false);
        clicked_link_keluhan.setVisible(false);
        clicked_link_rekammedis.setVisible(true);
        clicked_link_logout.setVisible(false);
    }//GEN-LAST:event_link_rekam_medisMouseClicked

    private void link_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link_logoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_link_logoutMouseClicked

    private void clicked_link_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clicked_link_dashboardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_clicked_link_dashboardMouseClicked

    private void clicked_link_pasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clicked_link_pasienMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_clicked_link_pasienMouseClicked

    private void clicked_link_rekammedisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clicked_link_rekammedisMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_clicked_link_rekammedisMouseClicked

    private void clicked_link_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clicked_link_logoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_clicked_link_logoutMouseClicked

    private void link_keluhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link_keluhanMouseClicked
        panel_content.removeAll();
        panel_content.repaint();
        panel_content.revalidate();
        
        panel_content.add(menu_keluhan);
        panel_content.repaint();
        panel_content.revalidate();
        
        clicked_link_dashboard.setVisible(false);
        clicked_link_pasien.setVisible(false);
        clicked_link_keluhan.setVisible(true);
        clicked_link_rekammedis.setVisible(false);
        clicked_link_logout.setVisible(false);
    }//GEN-LAST:event_link_keluhanMouseClicked

    private void clicked_link_keluhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clicked_link_keluhanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_clicked_link_keluhanMouseClicked

    private void btn_simpan_pasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpan_pasienMouseClicked
       try {
            String sql = "INSERT INTO `tb_pasien` VALUES ('%s','%s','%s','%s','%s','%s','%s','%s','%s','%s')";
            java.sql.Connection conn = (Connection)config.configDB();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(jd_tanggal_lahir.getDate());
            sql = String.format(
                sql,
                tf_id_pasien.getText(),
                tf_nama_lengkap.getText(),
                date,
                tf_nik.getText(),
                cmb_kelamin.getSelectedItem(),
                cmb_status_pernikahan.getSelectedItem(),
                cmb_agama.getSelectedItem(),
                tf_nomor_telepon.getText(),
                ta_alamat.getText(),
                tf_no_bpjs.getText()
            );
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil tersimpan");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Gagal disimpan"+ex);
        }
    }//GEN-LAST:event_btn_simpan_pasienMouseClicked

    private void tf_nikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nikActionPerformed

    private void btn_simpan_keluhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpan_keluhanMouseClicked
        try {
           
            String sql = "INSERT INTO `tb_keluhan`(`id_keluhan`, `id_rekam_medis`, `id_poli`, `keluhan`, `id_dokter`) VALUES ('%s','%s','%s','%s','%s')";
            java.sql.Connection conn = (Connection)config.configDB();
            sql = String.format(
                sql,
                tf_id_keluhan.getText(),
                cmb_rekam_medis.getSelectedItem(),
                cmb_poli_tujuan.getSelectedItem(),
                ta_keluhan.getText(),
                cmb_dokter.getSelectedItem()
            );
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil tersimpan");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Gagal disimpan"+ex);
        }
    }//GEN-LAST:event_btn_simpan_keluhanMouseClicked

    private void cmb_rekam_medisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_rekam_medisActionPerformed
        setDataByIdRM();
    }//GEN-LAST:event_cmb_rekam_medisActionPerformed

    private void cmb_dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_dokterActionPerformed
        setJadwalByIdDokter();
    }//GEN-LAST:event_cmb_dokterActionPerformed

    private void cmb_poli_tujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_poli_tujuanActionPerformed
        setDokterByIdPoli();
    }//GEN-LAST:event_cmb_poli_tujuanActionPerformed

    private void tf_jadwal_dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_jadwal_dokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_jadwal_dokterActionPerformed

    private void link_owner_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link_owner_dashboardMouseClicked
        panel_content.removeAll();
        panel_content.repaint();
        panel_content.revalidate();
        
        panel_content.add(owner_dashboard);
        panel_content.repaint();
        panel_content.revalidate();
        
        //clicked effect
        clicked_owner_dashboard.setVisible(true);
        clicked_owner_karyawan.setVisible(false);
        clicked_owner_dokter.setVisible(false);
        clicked_owner_rekammedis.setVisible(false);
        clicked_owner_logout.setVisible(false);
    }//GEN-LAST:event_link_owner_dashboardMouseClicked

    private void link_owner_karyawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link_owner_karyawanMouseClicked
        panel_content.removeAll();
        panel_content.repaint();
        panel_content.revalidate();
        
        panel_content.add(owner_karyawan);
        panel_content.repaint();
        panel_content.revalidate();
        
        //clicked effect
        clicked_owner_dashboard.setVisible(false);
        clicked_owner_karyawan.setVisible(true);
        clicked_owner_dokter.setVisible(false);
        clicked_owner_rekammedis.setVisible(false);
        clicked_owner_logout.setVisible(false);
    }//GEN-LAST:event_link_owner_karyawanMouseClicked

    private void link_owner_dokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link_owner_dokterMouseClicked
        panel_content.removeAll();
        panel_content.repaint();
        panel_content.revalidate();
        
        panel_content.add(owner_dokter);
        panel_content.repaint();
        panel_content.revalidate();
        
        //clicked effect
        clicked_owner_dashboard.setVisible(false);
        clicked_owner_karyawan.setVisible(false);
        clicked_owner_dokter.setVisible(true);
        clicked_owner_rekammedis.setVisible(false);
        clicked_owner_logout.setVisible(false);
    }//GEN-LAST:event_link_owner_dokterMouseClicked

    private void link_owner_rekammedisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link_owner_rekammedisMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_link_owner_rekammedisMouseEntered

    private void link_owner_rekammedisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link_owner_rekammedisMouseClicked
        panel_content.removeAll();
        panel_content.repaint();
        panel_content.revalidate();
        
        panel_content.add(owner_rekammedis);
        panel_content.repaint();
        panel_content.revalidate();
        
        //clicked effect
        clicked_owner_dashboard.setVisible(false);
        clicked_owner_karyawan.setVisible(false);
        clicked_owner_dokter.setVisible(false);
        clicked_owner_rekammedis.setVisible(true);
        clicked_owner_logout.setVisible(false);
    }//GEN-LAST:event_link_owner_rekammedisMouseClicked

    private void tf_nama_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nama_karyawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nama_karyawanActionPerformed

    private void tf_id_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_id_karyawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_id_karyawanActionPerformed

    private void tf_nik_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nik_karyawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nik_karyawanActionPerformed

    private void tf_username_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_username_karyawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_username_karyawanActionPerformed

    private void tf_no_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_no_karyawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_no_karyawanActionPerformed

    private void tf_password_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_password_karyawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_password_karyawanActionPerformed

    private void btn_tambah_karyawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambah_karyawanMouseClicked
        try {
            String sql = "INSERT INTO `tb_karyawan` VALUES ('%s','%s','%s','%s','%s','%s','%s', 'admin')";
            java.sql.Connection conn = (Connection)config.configDB();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(tanggal_lahir.getDate());
            sql = String.format(
                sql,
                tf_id_karyawan.getText(),
                tf_nama_karyawan.getText(),
                date,
                tf_nik_karyawan.getText(),
                cmb_kelamin.getSelectedItem(),
                cmb_jenis_kelamin_karyawan.getSelectedItem(),
                ta_alamat_karyawan.getText(),
                tf_password_karyawan.getText()
            );
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil tersimpan");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Gagal disimpan"+ex);
        }
    }//GEN-LAST:event_btn_tambah_karyawanMouseClicked

    private void btn_tambah_dokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambah_dokterMouseClicked
        panel_tambah_dokter.setVisible(true);
    }//GEN-LAST:event_btn_tambah_dokterMouseClicked

    private void btn_batal_tambah_dokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batal_tambah_dokterMouseClicked
        panel_tambah_dokter.setVisible(false);
    }//GEN-LAST:event_btn_batal_tambah_dokterMouseClicked

    private void panel_tambah_dokterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_tambah_dokterMouseEntered
        panel_tambah_dokter.setVisible(true);
    }//GEN-LAST:event_panel_tambah_dokterMouseEntered

    private void tf_id_dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_id_dokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_id_dokterActionPerformed

    private void tf_nama_dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nama_dokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nama_dokterActionPerformed

    private void tf_no_dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_no_dokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_no_dokterActionPerformed

    private void tf_nik_dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nik_dokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nik_dokterActionPerformed

    private void tf_input_jadwal_dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_input_jadwal_dokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_input_jadwal_dokterActionPerformed

    private void tf_input_jadwal_dokter_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_input_jadwal_dokter_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_input_jadwal_dokter_editActionPerformed

    private void tf_nik_dokter_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nik_dokter_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nik_dokter_editActionPerformed

    private void tf_no_dokter_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_no_dokter_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_no_dokter_editActionPerformed

    private void tf_nama_dokter_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nama_dokter_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nama_dokter_editActionPerformed

    private void tf_id_dokter_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_id_dokter_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_id_dokter_editActionPerformed

    private void btn_batal_tambah_dokter1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batal_tambah_dokter1MouseClicked
        panel_edit_dokter.setVisible(false);
    }//GEN-LAST:event_btn_batal_tambah_dokter1MouseClicked

    private void panel_edit_dokterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_edit_dokterMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_edit_dokterMouseEntered

    private void btn_input_dokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_input_dokterMouseClicked
        try {
            String sql = "INSERT INTO `tb_dokter` VALUES ('%s','%s','%s','%s','%s','%s','%s', '%s')";
            java.sql.Connection conn = (Connection)config.configDB();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(jd_ttl_dokter.getDate());
            sql = String.format(
                sql,
                tf_id_dokter.getText(),
                tf_nama_dokter.getText(),
                date,
                alamat_dokter.getText(),
                tf_nik_dokter.getText(),
                cmb_kelamin_dokter.getSelectedItem(),
                tf_input_jadwal_dokter.getText(),
                cmb_poli_tujuan_dokter.getSelectedItem()
            );
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil tersimpan");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Gagal disimpan"+ex);
        }
    }//GEN-LAST:event_btn_input_dokterMouseClicked

    private void btn_edit_dokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_dokterMouseClicked
        int row =tabel_dokter.getSelectedRow();
        String id_dokter =(tabel_dokter.getModel().getValueAt(row, 0).toString());
        try {
            String sql = "SELECT * FROM `tb_dokter` where id_dokter = '"+id_dokter+"'";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            if(res.next()){
//               SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//                Date date = sdf.format(res.getString(3));
                String date = res.getString(3);  
                Date date1 = new SimpleDateFormat("yyyy-MM-dd").parse(date);  
                
                tf_id_dokter_edit.setText(res.getString(1));
                tf_nama_dokter_edit.setText(res.getString(2));
                jd_ttl_dokter_edit.setDate(date1);
                alamat_dokter_edit.setText(res.getString(4));
                tf_nik_dokter_edit.setText(res.getString(5));
                cmb_kelamin_edit.setSelectedItem(res.getString(6));
                tf_input_jadwal_dokter_edit.setText(res.getString(7));
                cmb_poli_dokter_edit.setSelectedItem(res.getString(8));
                panel_edit_dokter.setVisible(true);
            }else{
                System.out.println("tidak ada data");
            }
        } catch (Exception e) {
            System.err.println("koneksi gagal " + e.getMessage());
        }
    }//GEN-LAST:event_btn_edit_dokterMouseClicked

    private void btn_update_dokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_update_dokterMouseClicked
        try {
            String sql = "UPDATE `tb_dokter` SET nama_dokter = '%s', ttl = '%s', alamat = '%s', nik = '%s', jenis_kelamin = '%s', jadwal = '%s', id_poli = '%s' where id_dokter = '%s'";
            java.sql.Connection conn = (Connection)config.configDB();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(jd_ttl_dokter_edit.getDate());
            sql = String.format(
                sql,
                tf_nama_dokter_edit.getText(),
                date,
                alamat_dokter_edit.getText(),
                tf_nik_dokter_edit.getText(),
                cmb_kelamin_edit.getSelectedItem(),
                tf_input_jadwal_dokter_edit.getText(),
                cmb_poli_dokter_edit.getSelectedItem(),
                tf_id_dokter_edit.getText()
            );
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            panel_edit_dokter.setVisible(false);
            getDataDokter();
            JOptionPane.showMessageDialog(null, "Data berhasil terupdate");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Gagal disimpan"+ex);
        }
    }//GEN-LAST:event_btn_update_dokterMouseClicked

    private void btn_hapus_dokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapus_dokterMouseClicked
        try {
            int row =tabel_dokter.getSelectedRow();
            String id_dokter =(tabel_dokter.getModel().getValueAt(row, 0).toString());
            String sql = "DELETE FROM `tb_dokter` where id_dokter = '"+id_dokter+"'";
            java.sql.Connection conn = (Connection)config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            getDataDokter();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Gagal disimpan"+ex);
        }
    }//GEN-LAST:event_btn_hapus_dokterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat_dokter;
    private javax.swing.JTextArea alamat_dokter_edit;
    private javax.swing.JLabel bg_dashboard;
    private javax.swing.JLabel bg_dashboard1;
    private javax.swing.JLabel bg_dashboard2;
    private javax.swing.JLabel bg_dashboard3;
    private javax.swing.JLabel bg_dashboard4;
    private javax.swing.JLabel bg_keluhan;
    private javax.swing.JLabel bg_pendaftaran;
    private javax.swing.JLabel bg_rekammedis;
    private javax.swing.JLabel bg_sidebar_admin;
    private javax.swing.JLabel bg_sidebar_owner;
    private javax.swing.JLabel bg_tambah_dokter;
    private javax.swing.JLabel bg_tambah_dokter1;
    private javax.swing.JLabel btn_batal_tambah_dokter;
    private javax.swing.JLabel btn_batal_tambah_dokter1;
    private javax.swing.JLabel btn_edit_dokter;
    private javax.swing.JLabel btn_hapus_dokter;
    private javax.swing.JLabel btn_input_dokter;
    private javax.swing.JLabel btn_simpan_keluhan;
    private javax.swing.JLabel btn_simpan_pasien;
    private javax.swing.JLabel btn_tambah_dokter;
    private javax.swing.JLabel btn_tambah_karyawan;
    private javax.swing.JLabel btn_update_dokter;
    private javax.swing.JLabel clicked_link_dashboard;
    private javax.swing.JLabel clicked_link_keluhan;
    private javax.swing.JLabel clicked_link_logout;
    private javax.swing.JLabel clicked_link_pasien;
    private javax.swing.JLabel clicked_link_rekammedis;
    private javax.swing.JLabel clicked_owner_dashboard;
    private javax.swing.JLabel clicked_owner_dokter;
    private javax.swing.JLabel clicked_owner_karyawan;
    private javax.swing.JLabel clicked_owner_logout;
    private javax.swing.JLabel clicked_owner_rekammedis;
    private javax.swing.JComboBox<String> cmb_agama;
    private javax.swing.JComboBox<String> cmb_dokter;
    private javax.swing.JComboBox<String> cmb_jenis_kelamin_karyawan;
    private javax.swing.JComboBox<String> cmb_kelamin;
    private javax.swing.JComboBox<String> cmb_kelamin_dokter;
    private javax.swing.JComboBox<String> cmb_kelamin_edit;
    private javax.swing.JComboBox<String> cmb_poli;
    private javax.swing.JComboBox<String> cmb_poli1;
    private javax.swing.JComboBox<String> cmb_poli_dokter_edit;
    private javax.swing.JComboBox<String> cmb_poli_tujuan;
    private javax.swing.JComboBox<String> cmb_poli_tujuan_dokter;
    private javax.swing.JComboBox<String> cmb_rekam_medis;
    private javax.swing.JComboBox<String> cmb_status_pernikahan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private com.toedter.calendar.JDateChooser jd_tanggal_lahir;
    private com.toedter.calendar.JDateChooser jd_ttl_dokter;
    private com.toedter.calendar.JDateChooser jd_ttl_dokter_edit;
    private javax.swing.JScrollPane jscroll_tabel_rekam_medis;
    private javax.swing.JScrollPane jscroll_tabel_rekam_medis1;
    private javax.swing.JScrollPane jscroll_tabel_rekam_medis2;
    private javax.swing.JLabel lbl_jumlah_dokter;
    private javax.swing.JLabel lbl_jumlah_dokter_owner;
    private javax.swing.JLabel lbl_jumlah_pegawai_owner;
    private javax.swing.JLabel lbl_jumlah_poli;
    private javax.swing.JLabel lbl_jumlah_poli_owner;
    private javax.swing.JLabel lbl_total_pasien;
    private javax.swing.JLabel lbl_total_pasien_owner;
    private javax.swing.JLabel link_dashboard;
    private javax.swing.JLabel link_keluhan;
    private javax.swing.JLabel link_logout;
    private javax.swing.JLabel link_owner_dashboard;
    private javax.swing.JLabel link_owner_dokter;
    private javax.swing.JLabel link_owner_karyawan;
    private javax.swing.JLabel link_owner_logout;
    private javax.swing.JLabel link_owner_rekammedis;
    private javax.swing.JLabel link_pendaftaran_pasien;
    private javax.swing.JLabel link_rekam_medis;
    private javax.swing.JPanel menu_dashboard;
    private javax.swing.JPanel menu_keluhan;
    private javax.swing.JPanel menu_pendaftaran;
    private javax.swing.JPanel menu_rekammedis;
    private javax.swing.JPanel owner_dashboard;
    private javax.swing.JPanel owner_dokter;
    private javax.swing.JPanel owner_karyawan;
    private javax.swing.JPanel owner_rekammedis;
    private javax.swing.JPanel panel_content;
    private javax.swing.JPanel panel_edit_dokter;
    private javax.swing.JPanel panel_sidebar;
    private javax.swing.JPanel panel_tambah_dokter;
    private javax.swing.JPanel sidebar_admin;
    private javax.swing.JPanel sidebar_owner;
    private javax.swing.JTextArea ta_alamat;
    private javax.swing.JTextArea ta_alamat_karyawan;
    private javax.swing.JTextArea ta_keluhan;
    private javax.swing.JTable tabel_dokter;
    private javax.swing.JTable tabel_rekam_medis;
    private javax.swing.JTable tabel_rekam_medis_karyawan;
    private com.toedter.calendar.JDateChooser tanggal_lahir;
    private javax.swing.JTextField tf_id_dokter;
    private javax.swing.JTextField tf_id_dokter_edit;
    private javax.swing.JTextField tf_id_karyawan;
    private javax.swing.JTextField tf_id_keluhan;
    private javax.swing.JTextField tf_id_pasien;
    private javax.swing.JTextField tf_input_jadwal_dokter;
    private javax.swing.JTextField tf_input_jadwal_dokter_edit;
    private javax.swing.JTextField tf_jadwal_dokter;
    private javax.swing.JTextField tf_nama_dokter;
    private javax.swing.JTextField tf_nama_dokter_edit;
    private javax.swing.JTextField tf_nama_karyawan;
    private javax.swing.JTextField tf_nama_lengkap;
    private javax.swing.JTextField tf_nama_lengkap_keluhan;
    private javax.swing.JTextField tf_nik;
    private javax.swing.JTextField tf_nik_dokter;
    private javax.swing.JTextField tf_nik_dokter_edit;
    private javax.swing.JTextField tf_nik_karyawan;
    private javax.swing.JTextField tf_nik_keluhan;
    private javax.swing.JTextField tf_no_bpjs;
    private javax.swing.JTextField tf_no_dokter;
    private javax.swing.JTextField tf_no_dokter_edit;
    private javax.swing.JTextField tf_no_karyawan;
    private javax.swing.JTextField tf_nomor_telepon;
    private javax.swing.JTextField tf_password_karyawan;
    private javax.swing.JTextField tf_username_karyawan;
    // End of variables declaration//GEN-END:variables
}
