/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package permata.medika.clinic.center;

/**
 *
 * @author nico
 */
public class PanelDashboard extends javax.swing.JPanel {

    /**
     * Creates new form PanelDashboard
     */
    public PanelDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_dashboard = new javax.swing.JLabel();

        setLayout(null);

        bg_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Panel - Dashboard - Admin.png"))); // NOI18N
        add(bg_dashboard);
        bg_dashboard.setBounds(0, 0, 1276, 856);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_dashboard;
    // End of variables declaration//GEN-END:variables
}
